apiVersion: apps/v1
kind: Deployment
metadata:
  name: to-do-backend-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: to-do-backend
  template:
    metadata:
      labels:
        app: to-do-backend
    spec:  
      containers:
        - name: to-do-backend
          image: vladibo/todo-backend:0.1.1