apiVersion: v1
kind: Service
metadata:
  name: to-do-backend-svc
spec:
  type: ClusterIP
  selector:
    app: to-do-backend # This is the app as declared in the deployment.
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3005