apiVersion: apps/v1
kind: Deployment
metadata:
  name: ping-pong-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ping-pong
  template:
    metadata:
      labels:
        app: ping-pong
    spec:
      volumes:
        - name: shared-pong-log
          persistentVolumeClaim: 
            claimName: log-output-claim  
      containers:
        - name: ping-pong
          image: vladibo/ping-pong:1.0.4
          volumeMounts: # Mount volume
          - name: shared-pong-log
            mountPath: /tmp/kube