apiVersion: apps/v1
kind: Deployment
metadata:
  name: logger-dep
  namespace: exercises
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logger
  template:
    metadata:
      labels:
        app: logger
    spec:
      volumes:
        - name: info-volume
          configMap:
            name: log-output-config
            items:
              - key: information.txt
                path: information.txt
        - name: shared-pong-log
          persistentVolumeClaim: 
            claimName: log-output-claim
      containers:
        - name: log-output
          image: vladibo/random-string-logger:1.0.11
          env:
            - name: MESSAGE
              valueFrom:
                configMapKeyRef:
                  name: log-output-config
                  key: MESSAGE
          volumeMounts: 
            - name: info-volume
              mountPath: /etc/config
            - name: shared-pong-log
              mountPath: /tmp/kube  