apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: log-output-ingress
  namespace: project
spec:
  rules:
  - http:
      paths:
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: to-do-backend-svc
            port:
              number: 2345        
      - path: /
        pathType: Prefix
        backend:
          service:
            name: to-do-svc
            port:
              number: 2345 
               
      