apiVersion: v1
kind: Service
metadata:
  name: to-do-svc
  namespace: project
spec:
  type: ClusterIP
  selector:
    app: to-do # This is the app as declared in the deployment.
  ports:
    - port: 2345
      protocol: TCP
      targetPort: 3000